# Generated by Django 2.1.7 on 2019-03-17 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=30, verbose_name='QQ号')),
                ('note', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '忽略QQ号',
                'verbose_name_plural': '忽略QQ号',
            },
        ),
        migrations.AlterModelOptions(
            name='keywordedresponse',
            options={'verbose_name': '关键词应答', 'verbose_name_plural': '关键词应答'},
        ),
        migrations.AlterField(
            model_name='keywordedresponse',
            name='keyword',
            field=models.TextField(verbose_name='关键词'),
        ),
        migrations.AlterField(
            model_name='keywordedresponse',
            name='response',
            field=models.TextField(verbose_name='应答'),
        ),
    ]
