# Generated by Django 2.1.7 on 2019-05-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='last_scan_timestamp',
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
