# Generated by Django 2.1.7 on 2019-05-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_battlecampaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modianuser',
            name='modian_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
