# Generated by Django 2.1.7 on 2019-05-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190519_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='battlecampaign',
            name='number_of_participants',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
